# Generated by Django 2.2.4 on 2019-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_1', models.IntegerField(default=130)),
                ('beacon_2', models.IntegerField(default=130)),
                ('beacon_3', models.IntegerField(default=130)),
                ('beacon_4', models.IntegerField(default=130)),
                ('beacon_5', models.IntegerField(default=130)),
                ('beacon_6', models.IntegerField(default=130)),
                ('beacon_7', models.IntegerField(default=130)),
                ('beacon_8', models.IntegerField(default=130)),
            ],
        ),
    ]
