# Generated by Django 2.2.4 on 2019-08-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='Beacons',
        ),
    ]
